---
- name: awscli config
  expect:
     command: aws configure
     responses:
         AWS Access Key ID: "{{AWS_ACCESS_KEY_ID}}"
         AWS Secret Access Key: "{{AWS_SECRET_ACCESS_KEY}}"
         Default region name: "{{AWS_DEFAUlT_REGION}}"
         Default output format: "json"

- name : get filtered ids
  command: cat /root/output.text
  register: my_items
 
- name: check the instances 
  shell: aws ec2 describe-instance-attribute --instance-id "{{ item }}" --attribute sriovNetSupport --output text | grep -v "simple" >/root/instanceids.text 2>&1
  with_items: "{{ my_items.stdout_lines }}"

- name: get file contents
  command: cat /root/instanceids.text
  register: id

- name: Stop Instances
  shell: aws ec2 stop-instances --instance-ids "{{item}}"
  with_items: "{{id.stdout_lines}}"
- pause:
   minutes: 1
- name: Enable enhanced networking
  shell: aws ec2 modify-instance-attribute --instance-id "{{item}}" --sriov-net-support simple
  with_items: "{{id.stdout_lines}}"

- name: Start Instance
  shell: aws ec2 start-instances --instance-ids "{{item}}"
  with_items: "{{id.stdout_lines}}"
